agent:
    backend: 'openai'  # 'ollama' or 'openai'
    model: 'gpt-4o-mini'
    temperature: .0
    history: 10
    action_rate: 1

environment:
    name: 'BlackjackLLM-v1'
    kwargs: null

experiment:
    parent: 'experiments'
    name: 'black_jack_gpt-4o-mini'
    use_datetime: true
    seed: 0
    save_gif: true
    gif_fps: 1
    num_runs: 10
    verbose: true