agent:
    backend: 'ollama'  # 'ollama' or 'openai'
    model: 'llama3.1'
    temperature: .8
    history: 10
    action_rate: 1

environment:
    name: 'LunarLanderLLM-v2'
    kwargs: null

experiment:
    parent: 'experiments'
    name: 'lunar_lander_llama3.1'
    use_datetime: true
    seed: 0