agent:
    backend: 'openai'  # 'ollama' or 'openai'
    model: 'gpt-4o'
    temperature: .0
    history: 50
    action_rate: 1

environment:
    name: 'TaxiLLM-v3'
    kwargs: null

experiment:
    parent: 'experiments'
    name: 'taxi_gpt-4o-mini'
    use_datetime: true
    seed: 0
    save_gif: false
    gif_fps: 1
    num_runs: 1
    verbose: true